- hosts: all
  become_user: root
  become: true
  tasks:
        - yum_repository: 
                description: Docker yum 
                name: docker2
                baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                gpgcheck: no
                state: present
        - package:
                name: "docker-ce-18.09.1-3.el7.x86_64"
                state: present
                skip_broken: yes
        - name: Docker service start
          service:
                name: docker
                state: started
                enabled: yes
        - name: Sdk install
          command: "pip3 install docker"
        - name: Download image
          docker_image:
                  name: httpd
                  source: pull
                  tag: latest
        - copy:
                content: |
                  <!DOCTYPE html>
                  <html>
                  <head>
                      <title>Welcome to My Website hosted on Docker Container</title>
                  </head>
                  <body>
                      <h1>Hello, welcome to my website hosted on HTTPD!</h1>
                  </body>
                  </html>
                dest: "/var/www/html/index.html"
        - name: Launching Container
          docker_container:
                  name: WebServer
                  image: httpd
                  state: started
                  exposed_ports:
                  - "80"
                  ports:
                  - "8888:80"



