---
- name: Setup HTTPD server in Docker container on EC2 instance
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install required packages for Docker
      dnf:
        name: 
          - dnf-plugins-core
          - docker
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker engine
      dnf:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest httpd image
      docker_image:
        name: httpd
        source: pull

    - name: Create a directory for the website content
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Write content to index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Welcome to HTTPD Server</title>
          </head>
          <body>
            <h1>Hello from HTTPD in a Docker container!</h1>
          </body>
          </html>

    - name: Create and start an httpd container
      docker_container:
        name: httpd_server
        image: httpd
        state: started
        ports:
          - "80:80"
        volumes:
          - /var/www/html:/usr/local/apache2/htdocs/
