---
- hosts: all
  become_user: root
  become: true
  tasks:

    - name: Install Apache HTTPD (apache2)
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Ensure Apache HTTPD is running and enabled
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Allow HTTP traffic
      ufw:
        rule: allow
        name: "Apache Full"

    - name: Deploy index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Welcome to Our Apache Server</title>
          </head>
          <body>
            <h1>Hello, World!</h1>
            <p>This is a test page served by Apache HTTPD on Ubuntu.</p>
          </body>
          </html>
